# Generated by Django 3.2.18 on 2023-03-10 16:27

import blog.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230306_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=blog.fields.CaseInsensitiveCharField(max_length=100, unique=True),
        ),
    ]
