# Generated by Django 3.2.18 on 2023-03-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_bucketlist_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketlist',
            old_name='added_on',
            new_name='created_on',
        ),
    ]
