# Generated by Django 3.2.18 on 2023-03-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230320_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='regions',
        ),
        migrations.AddField(
            model_name='post',
            name='regions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.category'),
            preserve_default=False,
        ),
    ]
